.TH PAD 1 2023-04-10 GNU

.SH NAME
pad \- Pad a string to a given length

.SH SYNOPSIS
.B pad STRING
[\fB\-l\fR \fILENGTH\fR]
[\fB\-c\fR \fICHAR\fR]
[\fB\-m\fR \fIMODE\fR]
[\fB\-s\fR \fISTRING\fR]

.SH DESCRIPTION
.B pad
is a small program to pad a string to a given length.

.SH OPTIONS
.TP
.B \-l, \-\-length LENGTH
sets the length of the result string (Default: 80)
.TP
.B \-c, \-\-character CHAR
sets the char to use for padding (Default: ' ')
.TP
.B \-m, \-\-mode MODE
sets the padding mode. Possible values are "left", "right", "centre" and "both" (Default: "both")
.TP
.B \-s, \-\-string STRING
sets the string that you want to pad. Use \-s explicitly if you want to pad an empty string.
.TP
.B \-h, \-\-help
show help message

.SH NOTES
If
.B pad
is given the mode "centre" a user specified length will be ignored.

If
.B pad
is given an unrecognized option, e.g. \-\-invalid, it is treated as an input string and will not abort the execution of the program.

.SH BUGS

No bugs are lnown at the moment.

.SH AUTHOR
zockerfreunde03/z0gg3r <zocker@10zen.eu>
